services:
  db:
    image: postgres:15-alpine
    container_name: portal_db
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: portal_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Отключаем безопасность для простоты (учеба всё-таки)
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Ограничиваем память, чтобы Мак не тормозил
    ports:
      - "9200:9200"
    restart: always
volumes:
  db_data:
