spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB
  mvc:
    view:
      suffix: .jsp

  datasource:
    url: jdbc:postgresql://localhost:5433/myproject
    username: myuser
    password: ${DB_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    # dialect определяется автоматически

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

# Логирование
logging:
  file:
    name: logs/application.log
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.mipt.portal: DEBUG

app:
  security:
    pepper: "szfdxghjdakslbnvcxagsftuyidolajskhdhsf123"


telegram:
  bot:
    name: "PhystechPortalBot"
    token: "8441149825:AAHWjnuLsOk2AZhctVFrppMgJvPWLD3J65I"