spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB
  mvc:
    view:
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5433/myproject?useUnicode=true&characterEncoding=UTF-8&charSet=UTF-8
    username: myuser
    password: ${DB_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true

  sql:
    init:
      mode: always
      separator: "^^"

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    # dialect определяется автоматически

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      auto-create: true
    consumer:
      group-id: portal-app
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Логирование
logging:
  file:
    name: logs/application.log
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.mipt.portal: DEBUG

app:
  security:
    pepper: "szfdxghjdakslbnvcxagsftuyidolajskhdhsf123"
  kafka:
    topic:
      audit: portal.audit.events
      user: portal.user.events
      announcement: portal.announcement.events
      moderation: portal.moderation.events
      booking: portal.booking.events
      comment: portal.comment.events
      support: portal.support.events
      notification: portal.notification.events
