ALTER TABLE ads DROP CONSTRAINT IF EXISTS ads_status_check;
ALTER TABLE ads ADD CONSTRAINT ads_status_check CHECK (status IN ('DRAFT', 'UNDER_MODERATION', 'ACTIVE', 'BOOKED', 'REJECTED', 'ARCHIVED', 'DELETED'));

ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram_username VARCHAR(255);

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS cancel_notification_sent_at TIMESTAMP;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMP;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS confirm_notification_sent_at TIMESTAMP;
